### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by subashtimalsina** [elinahovakimyan/react-native-month-picker#1]
When I implement this on React-Native V 0.61 it works fine on Debug mode but at release application, it made a crash. Please fix this quick.

**Comment by elinahovakimyan** [comment]
Hi @subashtimalsina ! Thanks for using this package. 

Can you please share your code or provide more details on what's the error message, at which step it crashes so that we can reproduce it?

**Comment by subashtimalsina** [comment]
It's done with some changes to your package. Thank you
